import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { listChecklists, type ChecklistSummary } from "../api/checklists";

export function ChecklistsPage() {
  const { user } = useAuth();
  const [items, setItems] = useState<ChecklistSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    listChecklists()
      .then((d) => setItems(d.items))
      .catch((e) => setErr(e instanceof Error ? e.message : "Failed to load checklists"))
      .finally(() => setLoading(false));
  }, []);

  if (!user) return null;

  return (
    <div className="page">
        <section className="welcome">
          <h1>
            My <span className="accent">Approval Checklists</span>
          </h1>
          <p>Every personalised checklist generated by the Regulatory Knowledge Engine.</p>
        </section>

        {err ? <div className="alert alert-error">{err}</div> : null}

        <section className="features">
          {loading ? (
            <p>Loading…</p>
          ) : items.length === 0 ? (
            <div className="empty-state">
              <p>No checklists yet.</p>
              <Link to="/checklists/new" className="btn btn-primary">Create your first checklist</Link>
            </div>
          ) : (
            <div className="feature-grid">
              {items.map((c) => (
                <div className="feature-card module-card" key={c.id}>
                  <div className="module-title-row">
                    <h3>{c.name}</h3>
                    <span className={`chip chip-risk-${(c.riskCategory ?? "none").toLowerCase()}`}>{c.riskCategory ?? "unclassified"}</span>
                  </div>
                  <p>{c._count.items} approvals · {c.unit?.name ?? "no unit"} · {new Date(c.createdAt).toLocaleDateString()}</p>
                  <Link to={`/checklists/${c.id}`} className="btn btn-ghost btn-sm">Open</Link>
                </div>
              ))}
            </div>
          )}
        </section>
      </div>
  );
}